// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0L0dJzmDr16yhnVqJGaBlIAfgkdGpAXE',
    appId: '1:750970776673:web:eb6b36dcc4d7d5be4cce20',
    messagingSenderId: '750970776673',
    projectId: 'flutterauth-f8ee0',
    authDomain: 'flutterauth-f8ee0.firebaseapp.com',
    storageBucket: 'flutterauth-f8ee0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftwsO1BNo3FU_1dWazG6DqqLuZTXDz8Y',
    appId: '1:750970776673:android:46cab7ff5ee0d3bc4cce20',
    messagingSenderId: '750970776673',
    projectId: 'flutterauth-f8ee0',
    storageBucket: 'flutterauth-f8ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxOp_1_qybieELinJNqcgIr4NV_JQobgM',
    appId: '1:750970776673:ios:c856b8b2d5bc6e284cce20',
    messagingSenderId: '750970776673',
    projectId: 'flutterauth-f8ee0',
    storageBucket: 'flutterauth-f8ee0.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxOp_1_qybieELinJNqcgIr4NV_JQobgM',
    appId: '1:750970776673:ios:7a40b97d1909010c4cce20',
    messagingSenderId: '750970776673',
    projectId: 'flutterauth-f8ee0',
    storageBucket: 'flutterauth-f8ee0.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
